base_url = "https://davidkoloski.me"

title = "David Koloski"
description = "Software Engineer, Game Designer, Web Developer"

generate_rss = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags"}
]

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "inspired-github"

[extra]
author = { name = "David Koloski" }